name: pub_publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v7
      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
      - name: 📦 Install Dependencies
        run: flutter pub get
      - name: 🌵 Dry Run
        run: dart pub publish --dry-run
      - name: 📢 Publish
        run: dart pub publish --force
